# Generated by Django 4.1.4 on 2023-01-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_bid_listing_alter_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='activity',
            field=models.BooleanField(default=True),
        ),
    ]
